### ISSUE TITLE
Calendarul de la cuvântul zilei arată rău la lățimi mici

### ISSUE THREAD

**Issue by CatalinFrancu** [dexonline/dexonline#478]
Nu știu cum să zic să-l reparăm.

* thumbnails mai mici;
* fără thumbnails;
* afișarea pe zile (31 de linii a câte o zi);
* ascunderea completă?

**Comment by danburzo** [comment]
Cam asta se poate obține cu:

```css
.wotdArchiveTable tbody td {
    display: block;
    width: auto;
    height: auto;
    font-size: 1.2em;
    text-align: left;
    border: none;
    background: #fff;
  }

  .wotdArchiveTable thead,
  .wotdArchiveTable tbody td:not(.activeMonth),
  .wotdArchiveTable .thumb {
    display: none;
  }

  .wotdArchiveTable tbody td > div {
    display: inline;
  }
```

<img width="322" alt="screen shot 2016-08-22 at 21 56 45" src="https://cloud.githubusercontent.com/assets/205375/17867475/587a3df0-68b3-11e6-9a38-9f99ae3a589c.png">
